"""Generate Karamat's one-page ATS-compliant resume PDF (ReportLab).

Follows the pdf-skill Report brief resume template: single column, no cover,
no TOC, Times New Roman, thin section rules, >=85% page fill.
"""
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle,
    KeepTogether,
)
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# ── Fonts (Windows system TTFs) ──
pdfmetrics.registerFont(TTFont('Times New Roman', r'C:\Windows\Fonts\times.ttf'))
pdfmetrics.registerFont(TTFont('Times New Roman-Bold', r'C:\Windows\Fonts\timesbd.ttf'))
pdfmetrics.registerFont(TTFont('Times New Roman-Italic', r'C:\Windows\Fonts\timesi.ttf'))
registerFontFamily('Times New Roman', normal='Times New Roman',
                   bold='Times New Roman-Bold', italic='Times New Roman-Italic')

# ━━ Color Palette (auto-generated by pdf.py palette.generate) ━━
# Intent: cold | Mode: minimal | Harmony: split_complementary
# Contrast: text:bg=14.49 | accent:bg=3.67
ACCENT       = colors.HexColor('#d4572d')
TEXT_PRIMARY = colors.HexColor('#202224')
TEXT_MUTED   = colors.HexColor('#7b8287')

# ── Styles ──
name_style = ParagraphStyle('Name', fontName='Times New Roman-Bold', fontSize=20.5,
                             leading=24, alignment=TA_CENTER, spaceAfter=2,
                             textColor=TEXT_PRIMARY)
headline_style = ParagraphStyle('Headline', fontName='Times New Roman', fontSize=11,
                                leading=13, alignment=TA_CENTER, spaceAfter=3,
                                textColor=ACCENT)
contact_style = ParagraphStyle('Contact', fontName='Times New Roman', fontSize=9.5,
                               leading=12, alignment=TA_CENTER, spaceAfter=4,
                               textColor=TEXT_MUTED)
section_title_style = ParagraphStyle('SectionTitle', fontName='Times New Roman-Bold',
                                     fontSize=12, leading=14, spaceBefore=6,
                                     spaceAfter=1.5, textColor=ACCENT)
job_title_style = ParagraphStyle('JobTitle', fontName='Times New Roman-Bold',
                                 fontSize=10.5, leading=12.8, spaceBefore=3.5,
                                 spaceAfter=1, textColor=TEXT_PRIMARY)
job_meta_style = ParagraphStyle('JobMeta', fontName='Times New Roman-Italic',
                                fontSize=9.3, leading=11.5, spaceAfter=2,
                                textColor=TEXT_MUTED)
bullet_style = ParagraphStyle('Bullet', fontName='Times New Roman', fontSize=9.5,
                              leading=11.8, leftIndent=12, bulletIndent=2,
                              spaceBefore=0.5, spaceAfter=0.5,
                              alignment=TA_LEFT, textColor=TEXT_PRIMARY)
body_style = ParagraphStyle('Body', fontName='Times New Roman', fontSize=9.6,
                            leading=12.2, spaceAfter=2, alignment=TA_LEFT,
                            textColor=TEXT_PRIMARY)
skills_style = ParagraphStyle('Skills', fontName='Times New Roman', fontSize=9.5,
                              leading=12, spaceAfter=1.5, alignment=TA_LEFT,
                              leftIndent=0, textColor=TEXT_PRIMARY)


def section_header(title):
    return [Paragraph(f'<b>{title}</b>', section_title_style),
            HRFlowable(width='100%', thickness=0.8, color=ACCENT,
                       spaceBefore=0, spaceAfter=4)]


def project_entry(title, meta, link_html, bullets):
    els = [Paragraph(f'<b>{title}</b>', job_title_style),
           Paragraph(f'{meta}<br/>{link_html}', job_meta_style)]
    for b in bullets:
        els.append(Paragraph(b, bullet_style, bulletText='•'))
    els.append(Spacer(1, 2))
    return [KeepTogether(els[:2])] + els[2:]


doc = SimpleDocTemplate(
    r'C:\Users\Karamat\Adaptive-RAG-Project\Karamat_Shirgaonkar_AI_Resume.pdf',
    pagesize=A4, leftMargin=1.4*cm, rightMargin=1.4*cm,
    topMargin=1.3*cm, bottomMargin=1.2*cm,
    title='Karamat Shirgaonkar - AI/LLM Systems Engineer Resume',
    author='Karamat Shirgaonkar', creator='Z.ai',
    subject='AI/LLM Systems Engineer and Data Engineer resume')

story = []

# ── Header ──
story.append(Paragraph('<b>KARAMAT NIJAMUDDIN SHIRGAONKAR</b>', name_style))
story.append(Paragraph('AI / LLM Systems Engineer  •  Data Engineer', headline_style))
story.append(Paragraph(
    'karamatsh19@gmail.com  |  +91 90829 86540  |  Mumbai, India  |  '
    '<link href="https://github.com/karamat552"><u><font color="#0000EE">github.com/karamat552</font></u></link>  |  '
    '<link href="https://linkedin.com/in/karamat552"><u><font color="#0000EE">linkedin.com/in/karamat552</font></u></link>  |  '
    'Live AI demo: <link href="https://adaptive-rag-enterprise.streamlit.app"><u><font color="#0000EE">adaptive-rag-enterprise.streamlit.app</font></u></link>',
    contact_style))

# ── Professional Summary ──
story.extend(section_header('PROFESSIONAL SUMMARY'))
story.append(Paragraph(
    'Computer Engineering graduate who builds and ships production AI systems: a live-deployed, '
    'self-correcting multi-agent RAG platform (LangGraph, FastAPI, PostgreSQL/pgvector) gated by '
    '43 CI tests and adversarial hallucination evals, plus an Azure Medallion lakehouse pipeline. '
    'Specializes in LLM systems engineered to fail safely — zero-trust auditing, refusal over '
    'hallucination, and token-cost discipline. Targeting AI/LLM Engineer and Data Engineer roles.',
    body_style))

# ── Technical Skills ──
story.extend(section_header('TECHNICAL SKILLS'))
for cat, vals in [
    ('Languages', 'Python, SQL (PostgreSQL), PySpark'),
    ('AI/LLM & RAG', 'LangGraph, LangChain, RAG (hybrid RRF search, pgvector HNSW, FlashRank reranking), '
     'FastEmbed/bge ONNX embeddings, semantic caching, structured LLM outputs (Pydantic), '
     'RAGAS-methodology evaluation, hallucination detection, Groq/Gemini APIs'),
    ('Backend & APIs', 'FastAPI, Uvicorn, REST, SSE streaming, token-bucket rate limiting, Prometheus metrics'),
    ('Cloud & Big Data', 'Azure Data Factory, Azure Databricks, ADLS Gen2, Azure Synapse, Medallion architecture'),
    ('Data & BI', 'PostgreSQL (Row-Level Security, CTEs), pgvector, Neon, Power BI star schema, Pandas'),
    ('DevOps & Testing', 'Docker, GitHub Actions CI, pytest, Git, Streamlit, httpx'),
    ('Classic ML', 'Scikit-learn (Logistic Regression, Random Forest, XGBoost), EDA, feature engineering'),
]:
    story.append(Paragraph(f'<b>{cat}:</b>  {vals}', skills_style))

# ── Featured Projects ──
story.extend(section_header('FEATURED PROJECTS'))

story.extend(project_entry(
    'Adaptive RAG — Enterprise Financial Intelligence Platform',
    'LangGraph  •  FastAPI  •  PostgreSQL/pgvector (RLS)  •  Docker  •  GitHub Actions CI  •  Streamlit',
    '<link href="https://github.com/karamat552/adaptive-rag-enterprise"><u><font color="#0000EE">github.com/karamat552/adaptive-rag-enterprise</font></u></link>  |  Live app + public API (green CI badge)',
    [
        'Architected and deployed a self-correcting multi-agent RAG platform (maker-checker: 3 parallel '
        'specialist agents → CIO synthesizer → zero-trust compliance auditor) over 186 indexed SEC-filing '
        'chunks; unverified answers trigger bounded rewrites or verified refusal, while certified answers '
        'serve in ~3s at zero token cost from an epoch-guarded semantic cache.',
        'Built fail-closed multi-tenant persistence on PostgreSQL + pgvector: least-privilege runtime role '
        'under Row-Level Security, hybrid RRF search (HNSW cosine + trigram keyword, k=60) with local ONNX '
        'embeddings and reranking, and corpus-epoch cache invalidation for zero-downtime re-ingestion.',
        'Hardened the FastAPI serving layer to SRE standards — per-IP token-bucket rate limiting, SSE '
        'streaming with keep-alive heartbeats, client-disconnect cancellation that halts in-flight LLM '
        'token spend, split liveness/readiness probes, Prometheus counters + latency histograms, and '
        'request-ID-correlated structured logs.',
        'Authored an adversarial evaluation harness that programmatically tampers verified figures '
        '(+$1M shifts, fabricated citations) and proves the live auditor rejects 8/8 tampered drafts '
        'before they can poison the semantic cache — plus gold-set accuracy and RAGAS-methodology '
        'faithfulness/precision/relevancy scoring.',
        'Shipped 43 automated tests in a 3-job CI pipeline (unit → pgvector integration running as the '
        'RLS-bound role → Docker build); verification passes exposed and fixed real infrastructure bugs '
        '(pgvector extension-bootstrap deadlock, container cold-start cascading into LLM 429s, SSE '
        'disconnect accounting), documented in commit history and Architecture Decision Records.',
    ]))

story.extend(project_entry(
    'Azure End-to-End Medallion Lakehouse Pipeline',
    'Azure Data Factory  •  Databricks (PySpark)  •  ADLS Gen2  •  Synapse Serverless SQL  •  Power BI',
    '<link href="https://github.com/karamat552/Azure-Data-Engineering-Lakehouse"><u><font color="#0000EE">github.com/karamat552/Azure-Data-Engineering-Lakehouse</font></u></link>',
    [
        'Architected a Bronze-Silver-Gold pipeline: ADF ingestion from REST sources into ADLS Gen2, then '
        'PySpark cleaning, schema enforcement, and type transformations in Databricks via Managed '
        'Identity mounts — writing Silver-layer Parquet.',
        'Published Gold-layer Fact/Dimension tables via Synapse Serverless SQL (OPENROWSET + CETAS) and '
        'modeled a Power BI star schema (Import mode) — a production-style flow from raw ingestion to '
        'business-ready reporting.',
    ]))

story.append(KeepTogether([
    Paragraph('<b>Loan Approval Prediction</b>', job_title_style),
    Paragraph('Python  •  Scikit-learn  •  Pandas  —  '
              '<link href="https://github.com/karamat552/loan-approval-prediction"><u><font color="#0000EE">github.com/karamat552/loan-approval-prediction</font></u></link>',
              job_meta_style),
    Paragraph('Benchmarked 6 Scikit-learn classifiers on a real-world loan dataset with evidence-based '
              'selection (confusion-matrix driven) and domain-specific null imputation.',
              bullet_style, bulletText='•'),
]))

# ── Education & Certifications ──
story.extend(section_header('EDUCATION & CERTIFICATIONS'))
edu = [
    [Paragraph('<b>B.E., Computer Engineering</b>', body_style),
     Paragraph('Rizvi College of Engineering, Mumbai  |  2022 – 2025', job_meta_style)],
    [Paragraph('<b>Diploma, Computer Engineering</b>', body_style),
     Paragraph('Vidyalankar Polytechnic, Mumbai  |  2019 – 2022', job_meta_style)],
    [Paragraph('<b>Complete Data Science Course</b>', body_style),
     Paragraph('Grow Data Skills  |  June 2026', job_meta_style)],
]
edu_table = Table(edu, colWidths=[doc.width * 0.42, doc.width * 0.58], hAlign='CENTER')
edu_table.setStyle(TableStyle([
    ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ('LEFTPADDING', (0, 0), (-1, -1), 0),
    ('RIGHTPADDING', (0, 0), (-1, -1), 4),
    ('TOPPADDING', (0, 0), (-1, -1), 1),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 1),
]))
story.append(edu_table)

doc.build(story)
print('RESUME_PDF_BUILT')
